/*--CLASS DB - DATABASE SCRIPT--*/

/*--AIASSISTANT DATABASE SCRIPT--*/

/*--Drop tables--*/
DROP TABLE IF EXISTS tbl_demonstration;
DROP TABLE IF EXISTS tbl_feedback;
DROP TABLE IF EXISTS tbl_eventregistry;
DROP TABLE IF EXISTS tbl_events;
DROP TABLE IF EXISTS tbl_faq;
DROP TABLE IF EXISTS tbl_staff;
DROP TABLE IF EXISTS tbl_roles;
DROP TABLE IF EXISTS tbl_reports;
DROP TABLE IF EXISTS tbl_countries;

/*Table reports*/
CREATE TABLE tbl_reports(
    REPORTID INT PRIMARY KEY, 
    REPORTNAME VARCHAR(200) NULL DEFAULT NULL, 
    CATEGORY VARCHAR(100) NULL DEFAULT NULL, 
    PREVIEW VARCHAR(100) NULL DEFAULT NULL
);

/*Table countries*/
CREATE TABLE tbl_countries(
    COUNTRYID   INT NOT NULL PRIMARY KEY,    
    COUNTRY     VARCHAR(100) NOT NULL,
    CAPITALCITY VARCHAR(50)  NOT NULL,
    CONTINENT   VARCHAR(50)  NOT NULL,
    CURRENCY    VARCHAR(20)  NOT NULL,
    COUNTRYCODE VARCHAR(5)   NOT NULL, 
    TELCODE     VARCHAR(10)  NOT NULL
);

/*Table roles*/
CREATE TABLE tbl_roles(
    ROLEID INT PRIMARY KEY NOT NULL,
    ROLE VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL
);

/*Table staff*/
CREATE TABLE tbl_staff(
    STAFFID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,       
    FIRSTNAME VARCHAR(30) NOT NULL,
    SURNAME VARCHAR(30) NOT NULL,
    GENDER CHAR(1) NOT NULL,      
    DOB DATE NULL DEFAULT NULL,         
    EMAILADDRESS VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL, /* Increased to store SHA2 hash */
    ROLEID INT NOT NULL,
    COUNTRYID INT NOT NULL,
    DATEREGISTERED DATE NULL DEFAULT NULL,
    FOREIGN KEY (ROLEID) REFERENCES tbl_roles(ROLEID),
    FOREIGN KEY (COUNTRYID) REFERENCES tbl_countries(COUNTRYID)
);

CREATE UNIQUE INDEX EMAILADDRESS ON tbl_staff(EMAILADDRESS);

/*Table faq*/
CREATE TABLE tbl_faq(
    FAQID INT PRIMARY KEY, 
    FAQUESTION VARCHAR(50) NULL DEFAULT NULL,  
    FAQANSWER VARCHAR(100) NULL DEFAULT NULL
);

/*Table events*/
CREATE TABLE tbl_events(
    EVENTID INT PRIMARY KEY,
    EVENTTITTLE VARCHAR(30) NULL DEFAULT NULL, 
    EVENTDESCRIPTION VARCHAR(300) NOT NULL, 
    VANUE VARCHAR(30) NULL DEFAULT NULL, 
    EVENTDATE DATE NOT NULL,
    EVENTTIME TIME NOT NULL
);

/*Table event registry*/
CREATE TABLE tbl_eventregistry(
    REGISTRATIONID INT PRIMARY KEY NOT NULL,
    FIRSTNAME VARCHAR(30) NOT NULL,
    SURNAME VARCHAR(30) NOT NULL,       
    EMAILADDRESS VARCHAR(100) NOT NULL,
    PHONENUMBER VARCHAR(30) NOT NULL,
    COMPANYNAME VARCHAR(30) NOT NULL,
    EVENTID INT NOT NULL,
    COUNTRYID INT NOT NULL,
    FOREIGN KEY (EVENTID) REFERENCES tbl_events(EVENTID),
    FOREIGN KEY (COUNTRYID) REFERENCES tbl_countries(COUNTRYID)
);

CREATE UNIQUE INDEX EMAILADDRESS ON tbl_eventregistry(EMAILADDRESS);

/*Table feedback - Updated structure*/
CREATE TABLE tbl_feedback(
    FEEDBACKID INT AUTO_INCREMENT PRIMARY KEY,
    FIRSTNAME VARCHAR(50) NOT NULL, 
    LASTNAME VARCHAR(50) NOT NULL,  
    EMAILADDRESS VARCHAR(100) NULL DEFAULT NULL,  
    PHONENUMBER VARCHAR(30) NULL DEFAULT NULL,
    FEEDBACK TEXT NOT NULL,
    FEEDBACKTYPE VARCHAR(50) NOT NULL,
    RATING INT NULL DEFAULT NULL
);

CREATE UNIQUE INDEX EMAILADDRESS ON tbl_feedback(EMAILADDRESS);

/*Table demonstration*/
CREATE TABLE tbl_demonstration(
    DEMONSTRATIONID INT PRIMARY KEY,
    FIRSTNAME VARCHAR(30) NOT NULL,
    LASTNAME VARCHAR(30) NOT NULL,
    EMAILADDRESS VARCHAR(100) NOT NULL,
    PHONENUMBER VARCHAR(30) NOT NULL,
    COMPANYNAME VARCHAR(30) NOT NULL,
    INTERESTDESCRIPTION VARCHAR(300) NOT NULL,
    COUNTRYID INT NOT NULL,
    STAFFID INT NOT NULL,
    DEMOSTATE CHAR(1) NOT NULL,
    FOREIGN KEY (COUNTRYID) REFERENCES tbl_countries(COUNTRYID),
    FOREIGN KEY (STAFFID) REFERENCES tbl_staff(STAFFID)
);

/*table countries*/
insert into tbl_countries values (1,'Algeria','Algier','Africa','DZD','DZ','00213');
insert into tbl_countries values (2,'Angola','Luanda','Africa','AOA','AO','00244');
/* ... rest of the insert statements remain the same ... */
insert into tbl_countries values (250,'Venezuela','Caracas','South America','VEB','VE','0058');
insert into tbl_countries values (251,'Virgin Islands, U.s.','Charlotte Amalie','South America','USD','VI','001340');

/*table roles*/
INSERT INTO tbl_roles VALUES (1,'Administrator','All members who are administrators');
INSERT INTO tbl_roles VALUES (2,'Demonstator','All members who are demonstrators');

/*table staff*/
INSERT INTO tbl_staff VALUES (1, 'ADMIN','01','F','1999-01-01','Admin@root.manage',SHA2('Rootpassword', 256),1,5,'2025-01-01');

