<?php
/**
 * reportViewer.php - Display generated reports
 * Shows detailed report data based on selected report
 */

// Start the session
session_start();

// Include the data access layer and report class
require_once 'DataAccess.php';
require_once 'ReportClass.php';

// Create instance of DataAccess class
$da = new DataAccess();
$reportClass = new ReportClass();

// Check if user is logged in and is an admin
if (!$da->isLoggedIn() || !$da->isAdmin()) {
    // Not logged in or not an admin, redirect to login
    header("Location: login.php");
    exit;
}

// Check if report ID is provided
if (!isset($_GET['reportId']) || empty($_GET['reportId'])) {
    header("Location: Reports.php");
    exit;
}

$reportId = intval($_GET['reportId']);

// Get report details
$reportDetails = $da->GetReportDetails($reportId);
if (empty($reportDetails)) {
    header("Location: Reports.php");
    exit;
}

// Execute report
$reportData = $da->ExecuteReport($reportId);

// Set page title
$pageTitle = $reportDetails['REPORTNAME'] . ' | AI Solutions';

// Start output buffering to capture content
ob_start();
?>

<div class="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-8">
    <div class="flex justify-between items-center mb-6">
        <h1 class="text-2xl font-bold text-gray-800"><?php echo htmlspecialchars($reportDetails['REPORTNAME']); ?></h1>
        <div>
            <button onclick="window.print()" class="bg-green-600 hover:bg-green-700 text-white py-2 px-4 rounded mr-2">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline-block mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
                </svg>
                Print
            </button>
            <a href="Reports.php" class="bg-indigo-600 hover:bg-indigo-700 text-white py-2 px-4 rounded">
                Back to Reports
            </a>
        </div>
    </div>

    <div class="bg-white shadow-md rounded-lg overflow-hidden">
        
        <div class="p-6">
            <?php if (empty($reportData)): ?>
                <div class="bg-yellow-100 border-l-4 border-yellow-500 text-yellow-700 p-4">
                    <p>No data available for this report.</p>
                </div>
            <?php else: ?>
                <div class="overflow-x-auto">
                    <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                            <tr>
                                <?php
                                // Get column headers from first row
                                $headers = array_keys($reportData[0]);
                                foreach ($headers as $header):
                                ?>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        <?php echo htmlspecialchars($header); ?>
                                    </th>
                                <?php endforeach; ?>
                            </tr>
                        </thead>
                        <tbody class="bg-white divide-y divide-gray-200">
                            <?php foreach ($reportData as $row): ?>
                                <tr>
                                    <?php foreach ($row as $key => $value): ?>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                            <?php echo htmlspecialchars($value); ?>
                                        </td>
                                    <?php endforeach; ?>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            <?php endif; ?>
        </div>
    </div>
    
    <div class="mt-8 text-sm text-gray-500">
        <p>Report generated on: <?php echo date('F j, Y, g:i a'); ?></p>
        <p>Generated by: <?php echo htmlspecialchars($_SESSION['user_name'] ?? 'Administrator'); ?></p>
    </div>
</div>

<?php
// Get the content from the buffer
$content = ob_get_clean();

// Include the master template
include 'master.php';
?>
